import { defineTool } from "@lovable.dev/mcp-js";
import { z } from "zod";

export default defineTool({
  name: "list_recent_signals",
  title: "List recent signals",
  description:
    "Return the most recent forex scalping signals generated by ScalpEdge. Optionally filter by pair, direction, or status. Returns entry, stop, TP levels, R:R, confidence, setup, and execution status.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of signals to return (default 10)."),
    pair: z.string().min(3).max(16).optional().describe("Filter by trading pair, e.g. EUR/USD."),
    direction: z.enum(["long", "short"]).optional().describe("Filter by trade direction."),
    status: z.string().min(2).max(24).optional().describe("Filter by signal status (pending, active, tp1, tp2, sl, expired, ...)."),
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, pair, direction, status }) => {
    const { createClient } = await import("@supabase/supabase-js");
    const supabase = createClient(
      process.env.SUPABASE_URL!,
      process.env.SUPABASE_PUBLISHABLE_KEY!,
      { auth: { persistSession: false, autoRefreshToken: false } },
    );
    let query = supabase
      .from("signals")
      .select(
        "id,pair,timeframe,setup,direction,entry,stop_loss,tp1,tp2,rr,confidence,session_score,status,htf_bias,created_at,executed_at,closed_at,outcome_r,metaapi_execution_status,metaapi_pnl",
      )
      .order("created_at", { ascending: false })
      .limit(limit ?? 10);
    if (pair) query = query.eq("pair", pair);
    if (direction) query = query.eq("direction", direction);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Failed to load signals: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { signals: data ?? [] },
    };
  },
});
