DROP FUNCTION IF EXISTS public.get_app_settings_public();

CREATE OR REPLACE FUNCTION public.get_app_settings_public()
 RETURNS TABLE(
   id text,
   paused boolean,
   trading_hours_start_utc integer,
   trading_hours_end_utc integer,
   session_config jsonb,
   active_td_key integer,
   key1_exhausted_at timestamptz,
   key2_exhausted_at timestamptz,
   key3_exhausted_at timestamptz,
   metaapi_auto_trade boolean,
   metaapi_min_confidence integer,
   metaapi_min_rr numeric,
   metaapi_fixed_lot numeric,
   metaapi_region text,
   metaapi_symbol_suffix text,
   metaapi_connected_at timestamptz,
   metaapi_configured boolean,
   metaapi_token_configured boolean,
   metaapi_max_trades integer,
   metaapi_expiry_hours integer,
   metaapi_max_daily_loss_pct numeric,
   metaapi_risk_per_trade_pct numeric,
   metaapi_min_lot numeric,
   metaapi_max_lot numeric,
   metaapi_is_cent_account boolean,
   pair_auto_execute jsonb,
   setup_auto_execute jsonb,
   metaapi_active_mode text,
   metaapi_region_live text,
   metaapi_symbol_suffix_live text,
   metaapi_live_configured boolean,
   metaapi_live_token_configured boolean,
   metaapi_is_cent_account_live boolean,
   scan_interval_minutes integer,
   legacy_atr_multipliers_enabled boolean,
   legacy_sl_mult numeric,
   legacy_tp_mult numeric,
   veritas_sl_mult numeric,
   veritas_tp_mult numeric,
   veritas_min_hurst numeric,
   veritas_min_snr numeric,
   veritas_min_conf numeric,
   veritas_min_rr numeric,
   updated_at timestamptz
 )
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    s.id, s.paused, s.trading_hours_start_utc, s.trading_hours_end_utc,
    s.session_config, s.active_td_key,
    s.key1_exhausted_at, s.key2_exhausted_at, s.key3_exhausted_at,
    s.metaapi_auto_trade, s.metaapi_min_confidence, s.metaapi_min_rr,
    s.metaapi_fixed_lot, s.metaapi_region, s.metaapi_symbol_suffix,
    s.metaapi_connected_at,
    (s.metaapi_account_id IS NOT NULL) AS metaapi_configured,
    (s.metaapi_token IS NOT NULL AND length(s.metaapi_token) > 0) AS metaapi_token_configured,
    s.metaapi_max_trades, s.metaapi_expiry_hours, s.metaapi_max_daily_loss_pct,
    s.metaapi_risk_per_trade_pct, s.metaapi_min_lot, s.metaapi_max_lot,
    COALESCE(s.metaapi_is_cent_account, false) AS metaapi_is_cent_account,
    COALESCE(s.pair_auto_execute, '{}'::jsonb) AS pair_auto_execute,
    COALESCE(s.setup_auto_execute, '{
      "EMA Pullback": true,
      "BOS Retest": true,
      "Session Range Break": true,
      "VERITAS": false
    }'::jsonb) AS setup_auto_execute,
    COALESCE(s.metaapi_active_mode, 'demo') AS metaapi_active_mode,
    COALESCE(s.metaapi_region_live, 'london') AS metaapi_region_live,
    COALESCE(s.metaapi_symbol_suffix_live, '') AS metaapi_symbol_suffix_live,
    (s.metaapi_account_id_live IS NOT NULL) AS metaapi_live_configured,
    (s.metaapi_token_live IS NOT NULL AND length(s.metaapi_token_live) > 0) AS metaapi_live_token_configured,
    COALESCE(s.metaapi_is_cent_account_live, false) AS metaapi_is_cent_account_live,
    COALESCE(s.scan_interval_minutes, 15) AS scan_interval_minutes,
    COALESCE(s.legacy_atr_multipliers_enabled, false) AS legacy_atr_multipliers_enabled,
    COALESCE(s.legacy_sl_mult, 1) AS legacy_sl_mult,
    COALESCE(s.legacy_tp_mult, 1) AS legacy_tp_mult,
    COALESCE(s.veritas_sl_mult,   1.5)  AS veritas_sl_mult,
    COALESCE(s.veritas_tp_mult,   2.5)  AS veritas_tp_mult,
    COALESCE(s.veritas_min_hurst, 0.55) AS veritas_min_hurst,
    COALESCE(s.veritas_min_snr,   40)   AS veritas_min_snr,
    COALESCE(s.veritas_min_conf,  72)   AS veritas_min_conf,
    COALESCE(s.veritas_min_rr,    1.60) AS veritas_min_rr,
    s.updated_at
  FROM public.app_settings s
  WHERE s.id = 'singleton';
$function$;
