name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Triggers the build automatically on every change to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build Application
        run: bun run build
        env:
          VITE_SUPABASE_URL: "https://supabase.co"
          VITE_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2eGl3cWJ1dXJ3a3N2anFzdW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyMDMyNDIsImV4cCI6MjA5NDc3OTI0Mn0.XazR4Te9STYeIYe-9sHbSWnn6jZX229QbIEvm1-9UU4"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .output --project-name=tanstack-start-app
